services:
  voice-diary-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voice-diary-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - voice-diary-api
    networks:
      - voice-diary
      - homelab-net

  voice-diary-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voice-diary-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ../../volumes/voice-diary/uploads:/app/uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://voicediaryuser:voicediarypass@voice-diary-db:5432/voicediary
    depends_on:
      - voice-diary-db
    networks:
      - voice-diary
      - homelab-net

  voice-diary-db:
    image: postgres:15-alpine
    container_name: voice-diary-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=voicediary
      - POSTGRES_USER=voicediaryuser
      - POSTGRES_PASSWORD=voicediarypass
    volumes:
      - ../../volumes/voice-diary/postgres:/var/lib/postgresql/data
    networks:
      - voice-diary

networks:
  homelab-net:
    external: true
  voice-diary:
    driver: bridge

volumes:
  node_modules:
