services:
  voice-diary-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - voice-diary-api
    networks:
      - voice-diary

  voice-diary-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./volumes/uploads:/app/uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://voicediaryuser:voicediarypass@voice-diary-db:5432/voicediary
    depends_on:
      - voice-diary-db
    networks:
      - voice-diary

  voice-diary-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=voicediary
      - POSTGRES_USER=voicediaryuser
      - POSTGRES_PASSWORD=voicediarypass
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - voice-diary

networks:
  voice-diary:
    driver: bridge

volumes:
  node_modules:
